FROM node:lts-slim as build

RUN mkdir -p /usr/src/app/node_modules
RUN chown -R node:node /usr/src/app

WORKDIR /usr/src/app

USER node

COPY --chown=node:node package*.json ./
RUN yarn install

COPY --chown=node:node . .

EXPOSE 3500